{
 "title": "Membench",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(latency_op_ns_v1_count[1m]))",
     "legendFormat": "TOTAL"
    },
    {
     "expr": "sum(rate(latency_op_ns_v1_count[1m])) by (op)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latencies - avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(latency_op_ns_v1_sum[1m]) / rate(latency_op_ns_v1_count[1m])",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "Latencies - p90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(latency_op_ns_v1_bucket[1m])) by (le, op))",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "Latencies - p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(latency_op_ns_v1_bucket[1m])) by (le, op))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latencies - p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(latency_op_ns_v1_bucket[1m])) by (le, op))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}